### ISSUE TITLE
useStaticPorts does not seems to take effect

### ISSUE THREAD

**Issue by SemanticBeeng** [Tapad/sbt-docker-compose#101]
`docker-compose.yml` contains

```
services:
  postgresql:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: yields
      POSTGRES_USER: yields
      POSTGRES_DB: yields
    ports:
      - "0:5432"
    volumes:
      - psql-data:/var/lib/postgresql/data
```
Running 
```
 sbt dockerComposeUp -useStaticPorts
```

Getting this container

```
+-----------------+--------------------+--------------+--------------+----------------+--------------+---------+
| Service         | Host:Port          | Tag Version  | Image Source | Container Port | Container Id | IsDebug |
+=================+====================+==============+==============+================+==============+=========+
| postgresql      | 192.168.80.1:32784 | 9.6-alpine   | defined      | 5432           | 696992939dcb |         |
+-----------------+--------------------+--------------+--------------+----------------+--------------+---------+
```
