### ISSUE TITLE
How to link my scala app's container, created by sbt-native-packager, to the dependency containers?

### ISSUE THREAD

**Issue by k0pernikus** [Tapad/sbt-docker-compose#104]
As a scala and sbt newbie while having experience with setting up docker complex development stacks via `docker` and `docker-compose`, I am confused by step 4 of the `Readme.md`:

> Define a docker-compose.yml file **which describes your component**, its dependent images and the links between them.

Highlighted part is the one where I am lost. How do I actually describe my component as I have no Dockerfile in place but my app's container is build directly through `sbt-native-packager`'s docker plugin:

```
packageName in Docker := packageName.value
dockerRepository := Some("some-internal-registry:5001")
dockerExposedPorts := Seq(8080)
dockerImageCreationTask := (publishLocal in Docker).value
```
In my `docker-compose.yml` I can describe the some services without problems:

```
redis:
  image: redis:3
cassandra:
  image: cassandra:3.11
mysql:
  image: mariadb:10.3
```

Yet I want to have something a long the lines of:

```
myApp:
    build: .
    links:
        - redis
        - mysql
        - cassandra

redis:
  image: redis:3
cassandra:
  image: cassandra:3.11
mysql:
  image: mariadb:10.3
```

Yet I have no `Dockerfile` on its own, I don't know how to reference the image created through the `sbt-native-packager` and don't know how to proceed from there.

I appreciate it if someone would be so kind as to shine more light on how to properly create a docker stack of one's own scala application. Thank you in advance.
