### ISSUE TITLE
dockerComposeTest does not clean up custom networks

### ISSUE THREAD

**Issue by Tillaert** [Tapad/sbt-docker-compose#55]
Given a docker compose file:

``` yaml
version: "2.1"

services:
  mongonode:
    image: mongo
    networks:
      - mongodb

networks:
  mongodb:
```

After running dockerComposeTest:

````
Going to remove 245930_mongonode_1
Error response from daemon: network 245930_default not found
````

And  ```docker network ls``` shows:

```
8b286c100378        295810_mongodb      bridge              local
````

It seems that dockerComposeTest uses ```docker-compose stop``` to stop the containers. ```docker-compose down``` will clean up resources properly.
